---
output_paths:
  linux   : build/output/linux/dataflow-runner
  darwin  : build/output/darwin/dataflow-runner
  windows : build/output/windows/dataflow-runner

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

packages:
  - repo     : "snowplow-generic"
    name     : "dataflow-runner"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict: false
    version  : <%= CMD['cat VERSION'] %>
    build_version : <%= ENV['TRAVIS_TAG'] %>
    artifacts:
      - prefix : "dataflow_runner_"
        suffix : "_linux_amd64"
        type   : "zip"
        binary_paths:
          - "{{ output_paths.linux }}"
      - prefix : "dataflow_runner_"
        suffix : "_darwin_amd64"
        type   : "zip"
        binary_paths:
          - "{{ output_paths.darwin }}"
      - prefix : "dataflow_runner_"
        suffix : "_windows_amd64"
        type   : "zip"
        binary_paths:
          - "{{ output_paths.windows }}.exe"
